Added multimap article
PoetaKodu/CppLangNet pull request #52
Opened 2021-11-05 15:56 UTC by Alzamer

## Description

Added multimap article

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🇺🇸 Translation  
- [ ] 🗑️ Chore

2021-11-05 18:36 UTC, PoetaKodu requested changes

2021-11-05 18:36 UTC, PoetaKodu commented on content/docs/std/containers/maps/multimap.mdx
> +  for (auto& [key, value] : player_stats)
There is a compilation error here (`player_stats` -> `potions`)

2021-11-05 18:36 UTC, PoetaKodu commented on content/docs/std/containers/maps/multimap.mdx
> +std::map, the only diffrence is the keys can repeat themselves. If the keys of both elements  are the
Two spaces after "elements"

2021-11-05 20:24 UTC, Alzamer commented on content/docs/std/containers/maps/multimap.mdx
> +  for (auto& [key, value] : player_stats)
Oh, copy-paste and I've overlooked it, sorry

2021-11-07 17:17 UTC, merged

2021-11-07 17:17 UTC, PoetaKodu commented
Accepted